name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install htmlhint stylelint eslint  # Install HTML, CSS, and JavaScript linting tools

    - name: Lint HTML, CSS, and JavaScript files
      run: |
        # Run HTML linting
        npx htmlhint "**/*.html"
        
        # Run JavaScript linting
        npx eslint "**/*.js"

