name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install   # If your project uses npm for dependencies

      - name: Build website
        run: |
          npm run build

      - name: Build Docker image
        run: docker build -t rayyounes/my-web-app:latest .
        working-directory: /home/runner/work/info408/Dockerfile

      - name: Push Docker image
        run: docker push rayyounes/my-web-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
