name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install htmlhint --global

    - name: Lint HTML
      run: htmlhint C:\Users\User\Documents\GitHub\info408\**/*.html
