name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install   # If your project uses npm for dependencies

      - name: Build website
        run: |
          npm run build

      - name: Build Docker image
        run: docker build -t rayyounes/my-web-app:latest .
        working-directory: .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push rayyounes/my-web-app:latest
